#!/bin/sh

command -v docker >/dev/null 2>&1 || { \
        echo >&2 "docker is required but could not be found.  Aborting."; \
        echo >&2 "To setup Docker: https://docs.docker.com/engine/getstarted/step_one/"; \
        exit 1; }

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)
        # is this xhost necessary? 
        # xhost + 127.0.0.1
        DISPLAY=host.docker.internal:0
        ;;
esac


docker run -ti   --user `id -u` \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v "$PWD":/current_dir -w /current_dir \
    master2gi-lt $@
